/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include "CarInfo.h"

CarInfo::CarInfo(void){
// TODO Auto-generated constructor stub
    isPKeyPressed = false;
	steerAngle = 0;
	shiftPos = CarInfo::SHIFT_POS_P;
	isRadaBack = false;
	isRadaFront = false;
	lightPos = 0;
	TireKey = 0xff;
	PageTrunKey = 0xff;
	isRTKPressed = false;
	isFDTKPressed = false;
//	isTrunLeft = false;	
//	isTrunRight= false;
//	isMiddle= false;
	for(int i=0;i<8;i++)
		radarVal[i] = 0;
	for(int i=0;i<4;i++)
		isDoorClose[i] = false;	
}

CarInfo::~CarInfo(void){
// TODO Auto-generated constructor stub
}