/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#ifndef DRVDS241_H_
#define DRVDS241_H_

#include "stm32f10x.h"
#include <Driver.h>

struct ResDS241 {

	uint32_t		RCC_APB2Periph_EN;
	GPIO_TypeDef	*GPIO_Port_EN;
	uint16_t		GPIO_Pin_EN;

	uint32_t		RCC_APB2Periph_TRFB;
	GPIO_TypeDef	*GPIO_Port_TRFB;
	uint16_t		GPIO_Pin_TRFB;

	uint32_t		RCC_APB2Periph_VODSEL;
	GPIO_TypeDef	*GPIO_Port_VODSEL;
	uint16_t		GPIO_Pin_VODSEL;

};

class DrvDS241 : public Driver {
public:
	DrvDS241(const ResDS241 *);
	~DrvDS241();
	int init(void);
	void enable(void);
	void disable(void);

private:
	const ResDS241 *_pRes;
};

#endif /* DRVDS241_H_ */
