/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#ifndef DRVM3366_H_
#define DRVM3366_H_

#include <Driver.h>

struct ResM3366 {
	uint32_t	RCC_APB2Periph_SW1;
	uint16_t	GPIO_Pin_SW1;
	GPIO_TypeDef*	GPIO_port_SW1;
	uint32_t	RCC_APB2Periph_SW2;
	uint16_t	GPIO_Pin_SW2;
	GPIO_TypeDef*	GPIO_port_SW2;
};

class DrvM3366 : public Driver {
public:
	DrvM3366(ResM3366 *resM3366);
	virtual ~DrvM3366();
	int init(void);
	int switch2vinx(const int i);
private:
	ResM3366 *_res;
};

#endif /* DRVM3366_H_ */
