/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef ACTIVATOR_H_
#define ACTIVATOR_H_

#include <DrvUSART.h>
#include "receiveStr.h"

static const int ID_STR_LEN	= 26;		// ID明文和密文字符串长度
static const int TIMEOUT_US	= 500000;	// 超时，单位：微秒
class Activator {
public:
	Activator(DrvUSART *pDrvUSART);
	~Activator();
	int activate(void);
    GetStr    *gpGetStr;
    OS_EVENT  *witerForStr;
    INT8U GetStrprio;
	DrvUSART *_pDrvUSART;
	#define BUF_SIZE	32
	char buf[BUF_SIZE];					// 接收ID明文    
    
};

#endif /* ACTIVATOR_H_ */
