/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef AUDIA62011BCOMKEEPINGTASK_H_
#define AUDIA62011BCOMKEEPINGTASK_H_

#include <ZTask.h>
#include <CanHub/CanHub.h>


typedef  uint32_t  CPU_SR;                                    /* Defines   CPU status register size (see Note #3).    */

class UARTResolutionTask : public ZTask {
public:

	UARTResolutionTask(uint8_t prio);
	void _doTask(void *p_arg);
};

class CanProtocol1Task: public ZTask {
public:
	CanProtocol1Task(uint8_t prio);
	void _doTask(void *p_arg);
private:
	CanHub::Slot *_pSlot;
};

class RearViewCameraTask : public ZTask {
public:
	RearViewCameraTask(uint8_t prio);
	void _doTask(void *p_arg);
};

#endif /* AUDIA62011BCOMKEEPINGTASK_H_ */
