/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef MAGOTAN_COMMON_H_
#define MAGOTAN_COMMON_H_

#include <stdint.h>
#include <ucos_ii.h>

namespace MagotanNS {
static const int32_t MAX_ABS_STEER_ANGLE		= 320;			// 转角绝对值最大值
static const int32_t MAX_ABS_CAN_STEER_ANGLE	= 0x2FFF;		// CAN帧中转角信息的最大绝对值
static const int32_t CAN_STEER_LEFT_BEGIN_VAL	= 0x0000;		// 方向盘往左打时CAN帧中转角信息的起始值
static const int32_t CAN_STEER_RIGHT_BEGIN_VAL	= 0x8000;		// 方向盘往右打时CAN帧中转角信息的起始值

static const uint32_t SHIFT_POS_MSG_ID = 0x359;
static const uint32_t STEERING_WHEER_ANGLE_MSG_ID = 0x3c3;
static const uint32_t RADAR_MSG_ID					= 0x54b;
static const uint32_t TURNING_LIGHT_STATUS_MSG_ID = 0x2c1;
//static const uint32_t ACC_STATUS_MSG_ID = 0x359;
static const uint32_t R_SHIFT_VAL = 0x70;

static const uint32_t DOOR_STATUS_ID			= 0x470;

static const uint32_t AIRCONDITION_STATUS_ID	= 0x3e1;
static const uint32_t FL_WINDOW_STATUS_ID		= 0x381;
static const uint32_t FR_WINDOW_STATUS_ID		= 0x3b5;
static const uint32_t BL_WINDOW_STATUS_ID		= 0x4b9;
static const uint32_t BR_WINDOW_STATUS_ID		= 0x4bd;
static const uint32_t KEY_STATUS_MSG_ID 		= 0x2c3;
static const uint32_t LOCK_STATUS_MSG_ID		= 0x291;
static const uint32_t WINODW_CONTROL_ID			= 0x181;
static const uint32_t LOCK_CONTROL_ID			= 0x391;


}

#endif /* COMMON_H_ */
